baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'iutdelens'

[[menu.main]] 
  name = "À propos" 
  url = "/a-propos-de" 
 
[[menu.main]] 
  name = "Blog" 
  url = "/blog"

[[menu.footer]] 
  name = "À propos" 
  url = "/a-propos-de"

[params]
  author = "Potpot"
  authorImage = "/profil/mon_avatar.png"

categories: ["Projet", "Développement web"]


